### PR TITLE
Include webpack 5 as peer dependence

### PR DESCRIPTION
**Pull request by eaglus**
Because of error while npm install project with webpack5

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: webpack@5.24.4
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.24.4" from the root project
npm ERR!   peer webpack@">=4.6.0" from @loadable/webpack-plugin@5.14.2
npm ERR!   node_modules/@loadable/webpack-plugin
npm ERR!     dev @loadable/webpack-plugin@"^5.14.2" from the root project
npm ERR!   15 more (@webpack-cli/configtest, babel-loader, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^1.12.9 || ^2.2.0 || ^3.x || ^4.x" from parallel-webpack@2.6.0
npm ERR! node_modules/parallel-webpack
npm ERR!   dev parallel-webpack@"^2.6.0" from the root project

### CODE REVIEW

**Comment by bin-umar** [comment]
because of this, doesn't work in npm 7! Please merge it asap

**Comment by eaglus** [comment]
@trivagoUserSync @rjanjic  @efegurkan  please merge this mr, we need it to work with webpack5. i checked work of parallel-webpack with webpack5, it works without any problems

**Comment by alverdal** [comment]
Is this repo no longer maintained? Or can somebody please merge this PR to support webpack 5 ?

**Comment by pago** [comment]
It's probably unmaintained. Perhaps @byara could help to get one last release out and then sunset the repo?

**Review by byara — APPROVED** [review]

**Review by byara — APPROVED** [review]

**Comment by byara** [comment]
Hey @pago, I was about to publish but it seems the package is not under trivago org anymore and only you and @efegurkan used to have access. What I can do is to republish it under trivago namespace and also update readme etc.

**Comment by efegurkan** [comment]
I double checked my account, I don't have access to any organization through my npm. I would either contact them and/or republish as you said.

**Comment by pago** [comment]
It seems like @rjanjic has maintainer rights. He should be able to give you access as well.

**Comment by byara** [comment]
The package is published under trivago org name: https://www.npmjs.com/package/@trivago/parallel-webpack.

**Pull request merged**
